name: 'Prepare Warewulf'
description: 'Prepare environment and Warewulf source code for testing and building'
inputs:
  go-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install gpgme (dependency)
      run: sudo apt-get install libgpgme-dev
      shell: bash

    - name: Setup go ${{ inputs.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Configure Warewulf
      run: make config
      shell: bash

    - name: Prepare vendor directory
      run: make vendor
      shell: bash
